=== piky/templator/src/main/resources/templates/zbx_template_new.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/zbx_template_new/" targetNamespace="http://www.example.org/zbx_template_new/">
    <element name="root" type="tns:rootType"/>
    <complexType name="templateType">
    	 <all>
    		<element name="name" type="string" maxOccurs="1" minOccurs="1"/>
    		<element name="description" type="string" maxOccurs="1" minOccurs="0"/>
    		<element name="sysObjectID" type="string"/>
    		<element name="discoveryRules" minOccurs="0" maxOccurs="1">
				<complexType>
	    			 <sequence>
	    				<element name="discoveryRule" maxOccurs="unbounded" minOccurs="0">
							<complexType>
				    			 <all>
				    				<element name="name" type="string" maxOccurs="1" minOccurs="1"/>
				    				<element name="key" type="string" maxOccurs="1" minOccurs="1"/>
				    				<element name="snmp_oid" type="string" maxOccurs="1" minOccurs="1"/>
				    				<element name="description" type="string" maxOccurs="1" minOccurs="0"/>
				    				<element name="filter" minOccurs="0" maxOccurs="1">
				    					<complexType>
				    						<sequence>
				    							<element name="evaltype" type="byte"/>
												<element name="formula" type="string"/>				    							
												<element name="conditions">
													<complexType>
														<sequence>
															<element name="condition" maxOccurs="unbounded" minOccurs="0">
																<complexType>
																	<sequence>
																		<element name="macro" type="string"/>
																		<element name="value" type="string"/>
																		<element name="operator" type="int"/>
																		<element name="formulaid" type="string"/>
																	</sequence>
																</complexType>
															</element>
														</sequence>
													</complexType>
												</element>
				    						</sequence>
				    					</complexType>
				    				</element>
				    			</all>
			    			</complexType>	    				
	    				</element>
	    			</sequence>
    			</complexType>    		
    		</element>
    		<element name="metrics">
    			<complexType>
	    			 	<sequence>
			    				<element name="cpuLoad" type="tns:metricType" maxOccurs="1" minOccurs="1"/>
			    				<element name="cpuUtil" type="tns:metricType" maxOccurs="1" minOccurs="0"/>
			    			<choice>
			    				<sequence>
			    					<element name="memoryUsed" type="tns:metricType" maxOccurs="1" minOccurs="1"/>
							    	<element name="memoryFree" type="tns:metricType" maxOccurs="1" minOccurs="1"/>
							    	<element name="memoryUsedPercentage" type="tns:metricType" maxOccurs="1" minOccurs="0"/>
			    				</sequence>
			    				<element name="memoryUsedPercentage" type="tns:metricType" maxOccurs="1" minOccurs="1"/>
			    			</choice>
			    			<element name="temperatureValue" type="tns:metricType" maxOccurs="1" minOccurs="1"></element>
							<element name="temperatureStatus" type="tns:metricType" maxOccurs="1" minOccurs="0"></element>
	    				</sequence>
    			</complexType>
    		</element>
    	</all>
    </complexType>
    
	<complexType name="rootType">
    	 <sequence>
    		<element name="template" type="tns:templateType" maxOccurs="unbounded" minOccurs="1"/>
    		<element name="value_maps" type="tns:valueMapsType" maxOccurs="1" minOccurs="0"/>
    	 </sequence>
    </complexType>
    
    <complexType name="metricType">
		<sequence>
			<element name="name" type="string" maxOccurs="1" minOccurs="1"/>
	 		<element name="group" type="tns:groupList" maxOccurs="1" minOccurs="1"/>
			<choice>
				<sequence>
					<element name="oid" type="string" maxOccurs="1" minOccurs="1"/>
				    <element name="snmpObject" type="string" maxOccurs="1" minOccurs="1"/>
				    <element name="mib" type="string" maxOccurs="1" minOccurs="0"/>	
				</sequence>
				<sequence>
					<element name="snmpObject" type="string" maxOccurs="1" minOccurs="1"/>
					<element name="expressionFormula" type="string" maxOccurs="1" minOccurs="1"/>
				</sequence>
			</choice>
			<choice maxOccurs="unbounded" minOccurs="0">
				<element name="description" type="string" maxOccurs="1" minOccurs="0"/>
			    <element name="vendorDescription" type="string" maxOccurs="1" minOccurs="0"/>
			    <element name="ref" type="string" maxOccurs="1" minOccurs="0"/>
			    <element name="history" type="string" maxOccurs="1" minOccurs="0"/>
			    <element name="trends" type="string" maxOccurs="1" minOccurs="0"/>
			    <element name="units" type="string" maxOccurs="1" minOccurs="0"/>
			    <element name="update" type="string" maxOccurs="1" minOccurs="0"/>
			    <element name="valueType" type="string" maxOccurs="1" minOccurs="0"/>
			    <element name="discoveryRule" type="string" maxOccurs="1" minOccurs="0"/>
			    <element name="metricLocation" type="string" maxOccurs="1" minOccurs="0"/>
			    <element name="valueMap" type="string" maxOccurs="1" minOccurs="0"/>
			    <element name="triggers" minOccurs="0" maxOccurs="1">
		    	<complexType>
		    		<sequence>
		    			<element name="trigger" type="tns:trigger" maxOccurs="unbounded" minOccurs="0"/>
		    		</sequence>
		    	</complexType>
		    </element>
			</choice>
	 	</sequence>
    </complexType>

    <complexType name="trigger">
		<all>
			<element name="id" type="string" maxOccurs="1" minOccurs="0"/>
			<element name="expression" type="string" maxOccurs="1" minOccurs="1"/>
	 		<element name="name" type="string" maxOccurs="1" minOccurs="1"/>
		    <element name="url" type="string" maxOccurs="1" minOccurs="0"/>
		    <element name="description" type="string" maxOccurs="1" minOccurs="0"/>
		  	<element name="priority" type="byte" maxOccurs="1" minOccurs="1"/>
		  	<element name="dependsOn" maxOccurs="1" minOccurs="0">
		  		<complexType>
		  			<sequence><element name="dependency" type="string" maxOccurs="unbounded" minOccurs="0"/></sequence>
		  		</complexType>
		  	</element>
	 	</all>
    </complexType>    

                    
    
<simpleType name="groupList">
    <restriction base="string">
        <enumeration value="Cpu"/>
        <enumeration value="Memory"/>
        <enumeration value="Temperature"/>
    </restriction>
</simpleType>

<complexType name="valueMapsType">
	<sequence>
		<element name="value_map" maxOccurs="unbounded">
			<complexType>
				<sequence>
					<element name="name"></element>
					<element name="mappings">
						<complexType>
							<sequence>
								<element name="mapping" maxOccurs="unbounded">
									<complexType>
									<sequence>
										<element name="value" type="string"/>
										<element name="newvalue" type="string"/>
									</sequence>
									</complexType>		
								</element>
							</sequence>
						</complexType>
					</element>
				</sequence>	
			</complexType>
		</element>
	</sequence>
</complexType>

</schema>

=== piky/templator/src/data/tmep/zbx_template_new2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://www.example.org/zbx_template_new/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/zbx_template_new/ ../../main/resources/templates/zbx_template_new.xsd ">
  <template>
	  <name>Cisco</name>
	  <metrics>
	    <cpuLoad>
	      <name>CPU Load</name>
	      <group>cpu</group>
	      <oid>{oid}</oid>
	    </cpuLoad>
	    <cpuUtil>
	      <name>CPU Utilization</name>
	      <group>cpu</group>
	      <oid>{oid}</oid>
	    </cpuUtil>
	    <memoryUsed>
	      <name>Memory Used</name>
	      <group>memory</group>
	      <oid>{oid}</oid>
	      <description>Memory Used in megabytes</description>
	    </memoryUsed>
	    <memoryFree>
	      <name>Memory free</name>
	      <group>memory</group>
	      <oid>{oid}</oid>
	    </memoryFree>
	  </metrics>
  </template>
</tns:root>

=== piky/templator/src/data/zabbix/template_juniper.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://www.example.org/zbx_template_new/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/zbx_template_new/ ../../main/resources/templates/zbx_template_new.xsd ">
  <template>
	  <name>Template Juniper</name>
	  <description>Template Juniper</description>
	  <sysObjectID>{sysobjectid}</sysObjectID>
	  <discoveryRules>
	  	<discoveryRule>
	  				<name>CPU and Memory Discovery</name>
                    <snmp_oid>discovery[{#SNMPVALUE},1.3.6.1.4.1.2636.3.1.13.1.5]</snmp_oid>
                    <key>jnxOperatingTable.discovery</key>
                    <description>Scanning JUNIPER-MIB::jnxOperatingTable for CPU and Memory 
                    http://kb.juniper.net/InfoCenter/index?page=content&amp;id=KB17526&amp;actp=search. Filter limits results to Routing Engines</description>
                    <filter>
                        <evaltype>0</evaltype>
                        <formula/>
                        <conditions>
							<condition>
                                <macro>{#SNMPVALUE}</macro>
                                <!-- <value>9\.[0-9]\.[0-9]\.[0-9]</value>  -->
                                <value>Routing Engine.*</value>
                                <operator>8</operator>
                                <formulaid>A</formulaid>
                            </condition>
                        </conditions>
                    </filter>
	  	</discoveryRule>
	  </discoveryRules>
	  <metrics>
	    <cpuLoad>
	      <oid>1.3.6.1.4.1.2636.3.1.13.1.21.{#SNMPINDEX}</oid>
	      <snmpObject>jnxOperating5MinLoadAvg[{#SNMPVALUE}]</snmpObject>
	      <mib>JUNIPER-MIB</mib>
	      <ref>http://kb.juniper.net/library/CUSTOMERSERVICE/GLOBAL_JTAC/BK26199/SRX%20SNMP%20Monitoring%20Guide_v1.1.pdf</ref>
	      <vendorDescription>The CPU Load Average over the last 5 minutesHere it will be shown as percentage valueZero if unavailable or inapplicable.</vendorDescription>
	      <discoveryRule>CPU and Memory Discovery</discoveryRule>
	    </cpuLoad>
	    <memoryUsedPercentage>
		  <oid>1.3.6.1.4.1.2636.3.1.13.1.11.{#SNMPINDEX}</oid>
	      <snmpObject>jnxOperatingBuffer[{#SNMPVALUE}]</snmpObject>
	      <mib>JUNIPER-MIB</mib>
	      <ref>http://kb.juniper.net/library/CUSTOMERSERVICE/GLOBAL_JTAC/BK26199/SRX%20SNMP%20Monitoring%20Guide_v1.1.pdf</ref>
	      <vendorDescription>The buffer pool utilization in percentageof this subject.  Zero if unavailable or inapplicable.</vendorDescription>
	      <discoveryRule>CPU and Memory Discovery</discoveryRule>
	    </memoryUsedPercentage>
	  </metrics>
  </template>
  
  </tns:root>

=== piky/templator/src/data/in/template_ubiquiti_airos.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://www.example.org/zbx_template_new/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/zbx_template_new/ ../../main/resources/templates/zbx_template_new.xsd ">
  <template>
  	  <class>Performance</class>
	  <name>Template Ubiquiti AirOS Performance</name>
	  <description>Template Ubiquiti AirOS Performance</description>
	  <sysObjectID>.1.3.6.1.4.1.10002.1</sysObjectID>
	  <metrics>
	    <cpuLoad>
	      <oid>.1.3.6.1.4.1.10002.1.1.1.4.2.1.3.2</oid>
	      <snmpObject>loadValue.2</snmpObject>
	      <mib>FROGFOOT-RESOURCES-MIB</mib>
	      <vendorDescription>5 minute load average of processor load.</vendorDescription>
	    </cpuLoad>
	    <memoryFree>
	      <oid>1.3.6.1.4.1.10002.1.1.1.1.2.0</oid>
	      <snmpObject>memFree</snmpObject>
	      <mib>FROGFOOT-RESOURCES-MIB</mib>
	      <multiplier>1024</multiplier>
	    </memoryFree>
	    <memoryTotal>
	      <oid>1.3.6.1.4.1.10002.1.1.1.1.1.0</oid>
	      <snmpObject>memTotal</snmpObject>
	      <mib>FROGFOOT-RESOURCES-MIB</mib>
	      <multiplier>1024</multiplier>
	    </memoryTotal>
	    <memoryUsedPercentage>
			 <snmpObject>memoryUsedPercentage</snmpObject>
			 <calculated>true</calculated>   	  
	    </memoryUsedPercentage>
	   </metrics>
  </template>
  </tns:root>

=== piky/templator/examples/cisco.out.xml
<?xml version="1.0" encoding="UTF-8"?><tns:root xmlns:tns="http://www.example.org/zbx_template_new/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/zbx_template_new/ ../../main/resources/templates/zbx_template_new.xsd ">
  <template>
	  <name>Cisco IOS Software releases 12.2(3.5) or later</name>
	  <description>Cisco IOS Software releases 12.2(3.5) or later</description>
	  <sysObjectID>{sysobjectid}</sysObjectID>
	  <metrics>
	    <cpuLoad>
<name>Cpu Load XSLT</name>
<group>cpu</group>
<oid>.1.3.6.1.4.1.9.9.109.1.1.1.1.8</oid>
<snmpObject>cpmCPUTotal5minRev</snmpObject>
<mib>CISCO-PROCESS-MIB</mib>
<ref>http://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/15215-collect-cpu-util-snmp.html</ref>
<vendorDescription>The cpmCPUTotal5minRev MIB object provides a more accurate view of the performance of the router over time than the MIB objects cpmCPUTotal1minRev and cpmCPUTotal5secRev . These MIB objects are not accurate because they look at CPU at one minute and five second intervals, respectively. These MIBs enable you to monitor the trends and plan the capacity of your network. The recommended baseline rising threshold for cpmCPUTotal5minRev is 90 percent. Depending on the platform, some routers that run at 90 percent, for example, 2500s, can exhibit performance degradation versus a high-end router, for example, the 7500 series, which can operate fine.</vendorDescription>
<description>Cpu load in %</description>
</cpuLoad>
	    <cpuUtil>
<name>Cpu Util</name>
<group>cpu</group>
<oid>{oid}</oid>
</cpuUtil>
	    <memoryUsed>
<name>Used memory</name>
<group>memory</group>
<oid>{oid}</oid>
<description>Used memory in bytes</description>
</memoryUsed>
	    <memoryFree>
<name>Free memory</name>
<group>memory</group>
<oid>{oid}</oid>
</memoryFree>
	  </metrics>
  </template>
  
    <template>
	  <name>Cisco IOS Software releases later to 12.0(3)T and prior to 12.2(3.5)</name>
	  <description>Cisco IOS Software releases later to 12.0(3)T and prior to 12.2(3.5)</description>
	  <sysObjectID>{sysobjectid}</sysObjectID>
	  <metrics>
	    <cpuLoad>
<name>Cpu Load XSLT</name>
<group>cpu</group>
<oid>.1.3.6.1.4.1.9.9.109.1.1.1.1.5</oid>
<snmpObject>cpmCPUTotal5min</snmpObject>
<mib>CISCO-PROCESS-MIB</mib>
<ref>http://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/15215-collect-cpu-util-snmp.html</ref>
<vendorDescription>The overall CPU busy percentage in the last 5 minute
period. This object deprecates the avgBusy5 object from 
the OLD-CISCO-SYSTEM-MIB. This object is deprecated
by cpmCPUTotal5minRev which has the changed range 
of value (0..100)</vendorDescription>
<description>Cpu load in %</description>
</cpuLoad>
	    <cpuUtil>
<name>Cpu Util</name>
<group>cpu</group>
<oid>{oid}</oid>
</cpuUtil>
	    <memoryUsed>
<name>Used memory</name>
<group>memory</group>
<oid>{oid}</oid>
<description>Used memory in bytes</description>
</memoryUsed>
	    <memoryFree>
<name>Free memory</name>
<group>memory</group>
<oid>{oid}</oid>
</memoryFree>
	  </metrics>
  </template>
  
  
      <template>
	  <name>Cisco IOS Software releases prior to 12.0(3)T</name>
	  <description>Cisco IOS Software releases prior to 12.0(3)T</description>
	  <sysObjectID>{sysobjectid}</sysObjectID>
	  <metrics>
	    <cpuLoad>
<name>Cpu Load XSLT</name>
<group>cpu</group>
<oid>.1.3.6.1.4.1.9.2.1.58</oid>
<snmpObject>avgBusy5</snmpObject>
<mib>OLD-CISCO-CPU-MIB</mib>
<ref>http://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/15215-collect-cpu-util-snmp.html</ref>
<vendorDescription>5 minute exponentially-decayed moving 
average of the CPU busy percentage.</vendorDescription>
<description>Cpu load in %</description>
</cpuLoad>
	    <cpuUtil>
<name>Cpu Util</name>
<group>cpu</group>
<oid>{oid}</oid>
</cpuUtil>
	    <memoryUsed>
<name>Used memory</name>
<group>memory</group>
<oid>{oid}</oid>
<description>Used memory in bytes</description>
</memoryUsed>
	    <memoryFree>
<name>Free memory</name>
<group>memory</group>
<oid>{oid}</oid>
</memoryFree>
	  </metrics>
  </template>
  
  <!-- multiple CPU:
  	Procedure for Devices with Multiple CPUs
If your IOS device has several CPUs, you must use CISCO-PROCESS-MIB
and its object cpmCPUTotal5minRev from the table called cpmCPUTotalTable , indexed with cpmCPUTotalIndex . This table allows CISCO-PROCESS-MIB to keep CPU statistics for different physical entities in the router, like different CPU chips, group of CPUs, or CPUs in different modules/cards. In case of a single CPU, cpmCPUTotalTable has only one entry.
Information about different physical entities in the router is stored in the entPhysicalTable of RFC 2737 standard-based ENTITY-MIB. You can link between two tables ( cpmCPUTotalTable and entPhysicalTable ) easily: each row of cpmCPUTotalTable has an object cpmCPUTotalPhysicalIndex that keeps the value of the entPhysicalIndex (index of entPhysicalTable ), and points to the entry in entPhysicalTable , correspondent to the physical entity for which these CPU statistics are maintained.
This implies that the IOS device must support both CISCO-PROCESS-MIB and ENTITY-MIB for you to be able to retrieve relevant information about CPU utilization. The only case where you do not need to have or use ENTITY-MIB is when you only have a single CPU.
  
http://www.cisco.com/c/en/us/support/docs/ip/simple-network-management-protocol-snmp/15215-collect-cpu-util-snmp.html
   -->
  
  
</tns:root>

=== piky/templator/src/data/result_step1/template_juniper.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://www.example.org/zbx_template_new/"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.example.org/zbx_template_new/ ../../main/resources/templates/zbx_template_new.xsd ">
  <template>
	     <name>Template Juniper</name>
	     <description>Template Juniper</description>
	     <sysObjectID>{sysobjectid}</sysObjectID>
	     <discoveryRules>
	  	     <discoveryRule>
	  				     <name>CPU and Memory Discovery</name>
                    <snmp_oid>discovery[{#SNMPVALUE},1.3.6.1.4.1.2636.3.1.13.1.5]</snmp_oid>
                    <key>jnxOperatingTable.discovery</key>
                    <description>Scanning JUNIPER-MIB::jnxOperatingTable for CPU and Memory 
                    http://kb.juniper.net/InfoCenter/index?page=content&amp;id=KB17526&amp;actp=search. Filter limits results to Routing Engines</description>
                    <filter>
                        <evaltype>0</evaltype>
                        <formula/>
                        <conditions>
							           <condition>
                                <macro>{#SNMPVALUE}</macro>
                                <!-- <value>9\.[0-9]\.[0-9]\.[0-9]</value>  -->
                                <value>Routing Engine.*</value>
                                <operator>8</operator>
                                <formulaid>A</formulaid>
                            </condition>
                        </conditions>
                    </filter>
	  	     </discoveryRule>
	     </discoveryRules>
	     <metrics>
	        <cpuLoad>
            <name>Cpu Load</name>
            <group>Cpu</group>
            <oid>1.3.6.1.4.1.2636.3.1.13.1.21.{#SNMPINDEX}</oid>
            <snmpObject>jnxOperating5MinLoadAvg[{#SNMPVALUE}]</snmpObject>
            <mib>JUNIPER-MIB</mib>
            <ref>http://kb.juniper.net/library/CUSTOMERSERVICE/GLOBAL_JTAC/BK26199/SRX%20SNMP%20Monitoring%20Guide_v1.1.pdf</ref>
            <vendorDescription>The CPU Load Average over the last 5 minutesHere it will be shown as percentage valueZero if unavailable or inapplicable.</vendorDescription>
            <description>Cpu load in %</description>
            <history>30</history>
            <trends>365</trends>
            <units>%</units>
            <update>30</update>
            <valueType>3</valueType>
            <discoveryRule>CPU and Memory Discovery</discoveryRule>
            <triggers>
               <trigger>
                  <expression>{Template Juniper:jnxOperating5MinLoadAvg[{#SNMPVALUE}].avg(300)}&gt;90</expression>
                  <name>CPU load is too high</name>
                  <url/>
                  <priority>3</priority>
                  <description/>
               </trigger>
            </triggers>
         </cpuLoad>
	        <memoryUsedPercentage>
            <name>Memory utilization</name>
            <group>Memory</group>
            <oid>1.3.6.1.4.1.2636.3.1.13.1.11.{#SNMPINDEX}</oid>
            <snmpObject>jnxOperatingBuffer[{#SNMPVALUE}]</snmpObject>
            <mib>JUNIPER-MIB</mib>
            <ref>http://kb.juniper.net/library/CUSTOMERSERVICE/GLOBAL_JTAC/BK26199/SRX%20SNMP%20Monitoring%20Guide_v1.1.pdf</ref>
            <vendorDescription>The buffer pool utilization in percentageof this subject.  Zero if unavailable or inapplicable.</vendorDescription>
            <description>Memory utilization in %</description>
            <history>30</history>
            <trends>365</trends>
            <units>%</units>
            <update>30</update>
            <valueType>3</valueType>
            <discoveryRule>CPU and Memory Discovery</discoveryRule>
            <triggers>
               <trigger>
                  <expression>{Template Juniper:jnxOperatingBuffer[{#SNMPVALUE}].avg(300)}&gt;90</expression>
                  <name>Memory utilization is too high</name>
                  <url/>
                  <priority>3</priority>
                  <description/>
               </trigger>
            </triggers>
         </memoryUsedPercentage>
	     </metrics>
  </template>
  
  </tns:root>
